sudo: false
language: generic
script: ./autogen.sh && ./configure && make && make nonexp-regtest

matrix:
  include:
    - env: COMPILER_NAME=gcc CC=gcc-7 CXX=g++-7
      addons:
        apt:
          packages:
            - gcc-7
          sources:
            - ubuntu-toolchain-r-test
    - env: COMPILER_NAME=clang CC=clang-3.8 CXX=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - llvm-toolchain-precise

