language: c
compiler: gcc
script: ./autogen.sh && ./configure && make && make nonexp-regtest
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
env:
  - CC=gcc-7 CXX=g++-7
