sudo: false
language: generic
script: ./autogen.sh && ./configure && make --quiet && make --quiet check && make nonexp-regtest

matrix:
  include:
    - env: COMPILER_NAME=gcc CC=gcc-7 CXX=g++-7
      addons:
        apt:
          packages:
            - gcc-7 g++-7 gdb libc6-dbg libc6-dbg:i386
          sources:
            - ubuntu-toolchain-r-test
    - env: COMPILER_NAME=clang CC=clang-3.8 CXX=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8 gdb libc6-dbg libc6-dbg:i386
          sources:
            - llvm-toolchain-precise

